services:
  - type: web
    name: hemix-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        renderType: portSync
      - key: SESSION_SECRET
        generateValue: true
      - key: AI_API_KEY
        sync: false
      - key: OWNER_NUMBER
        sync: false
      - key: BOT_PREFIX
        value: "."
      - key: AUTO_UPDATE
        value: "false"
    disk:
      name: hemix-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
